complaintbox/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.index,),

    path('studentreg/', views.studentreg, name='studentreg'),
    path('studentlog/', views.studentlog, name='studentlog'),
    path('profilestudent/', views.profilestudent, name='profilestudent'),
    path('viewstudent/', views.viewstudent, name='viewstudent'),
    path('cmpltform/',views.cmpltform,name="cmpltform"),
    path('logout/',views.logout,name='logout'),
    path('facultyreg/',views.facultyreg,name='facultyreg'),
    path('facultylog/',views.facultylog,name='facultylog'),
    path('viewcomplaint',views.viewcomplaint,name='viewcomplaint'),
    path('cupdate/<int:id>',views.cupdate,name="cupdate"),
    path('cupdate/cmupdate/<int:id>', views.cmupdate, name='cmupdate'),
    path('ackform/',views.ackform,name='ackform'),
    path('profilefaculty/',views.profilefaculty,name='profilefaculty'),
    path('ackview/', views.ackview, name='ackview'),
    path('viewfaculty/', views.viewfaculty, name='viewfaculty'),
    path('viewadmin/', views.viewadmin, name='viewadmin'),
    path('cmpltviewadmin/', views.cmpltviewadmin, name='cmpltviewadmin'),
    path('ackfaculty/', views.ackfaculty, name='ackfaculty'),
    path('viewfacultyack/', views.viewfacultyack, name='viewfacultyack'),
    path('sdelete/<int:id>',views.sdelete,name="sdelete"),
    path('sdelete/<int:id>',views.sdelete,name="sdelete"),
    path('supdate/',views.supdate,name="supdate"),
    path('supdate/updatestudent/<int:id>',views.updatestudent,name="updatestudent"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complaintbox/models.py
from django.db import models

class register(models.Model):
    userphoto=models.CharField(max_length=200)
    useremail=models.CharField(max_length=200)
    username=models.CharField(max_length=200)
    userphone=models.CharField(max_length=200)
    password=models.CharField(max_length=200)
class complaint(models.Model):
    userid=models.CharField(max_length=4)
    complaintto=models.CharField(max_length=10)
    date=models.CharField(max_length=10)
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    complaintmesg=models.CharField(max_length=800)
    status=models.CharField(max_length=200)
class faculty(models.Model):
    designation=models.CharField(max_length=200)
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    password=models.CharField(max_length=200)
class acknowledgement(models.Model):
    name=models.CharField(max_length=200)
    date=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    ackmesg=models.CharField(max_length=800)
class facack(models.Model):
    date=models.CharField(max_length=200)
    designation=models.CharField(max_length=200)
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    ackmesg=models.CharField(max_length=800)

complaintbox/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.hashers import check_password
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .models import *

def index(request):
    return render(request, 'index.html')

def studentreg(request):
    if request.method == 'POST':
        userphoto = request.FILES['userphoto']
        up = FileSystemStorage()
        img = up.save(userphoto.name, userphoto)
        useremail = request.POST.get('useremail')
        username = request.POST.get('username')
        userphone = request.POST.get('userphone')
        password = request.POST.get('password')
        log = register(useremail=useremail, username=username, userphone=userphone, password=password, userphoto=userphoto)
        log.save()
        return redirect(index)
    return render(request, 'register.html')

def studentlog(request):
    if request.method == 'POST':
        useremail = request.POST.get('useremail')
        password = request.POST.get('password')

        if useremail == 'admin@gmail.com' and password == 'admin':
            request.session['adminemail'] = useremail
            request.session['admin'] = 'admin'
            return render(request, 'index.html', {'status': 'Admin login successful'})

        elif register.objects.filter(useremail=useremail, password=password).exists():
            sdet = register.objects.get(useremail=useremail, password=password)
            request.session['student'] = sdet.id
            request.session['username'] = sdet.username
            request.session['useremail'] = sdet.useremail
            request.session['students'] = 'students'
            return render(request, 'index.html')
        

        else:
            return render(request, 'studentlogin.html', {'status': 'Incorrect credentials'})
        
    return render(request, 'studentlogin.html') 

def cmpltform(request):
    if request.method == 'POST':
        f=request.session['student']
        u=complaint.objects.filter(userid=f)
        complaintto = request.POST.get('complaintto')
        date = request.POST.get('date')
        name = request.POST.get('name')
        email = request.POST.get('email')
        complaintmesg = request.POST.get('complaintmesg')
        status = request.POST.get('status')
        log = complaint(userid=f,complaintto=complaintto, date=date, name=name, email=email, complaintmesg=complaintmesg, status=status)
        log.save()

    return render(request, 'complaintform.html')

def logout(request):
    session_keys = list(request.session.keys())
    for key in session_keys:
        del request.session[key]
    return redirect(index)

def facultyreg(request):
    if request.method == 'POST':
        designation = request.POST.get('designation')
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        log = faculty(designation=designation, name=name, email=email, password=password)
        log.save()
        return redirect(index)


    return render(request, 'facultyregister.html')


def facultylog(request):
    if request.method == 'POST':
        designation = request.POST.get('designation')
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            fdet = faculty.objects.get(designation=designation, email=email, password=password)
        except faculty.DoesNotExist:
            return render(request, 'facultylogin.html', {'status': 'Incorrect credentials'})

        request.session['faculty'] = fdet.id
        request.session['name'] = fdet.name
        request.session['email'] = fdet.email
        request.session['fdesig'] = fdet.designation

        request.session['faculties'] = 'faculties'
        return render(request, 'index.html')
        
    else:
        return render(request, 'facultylogin.html', {'status': ''})


def viewcomplaint(request):
    t=request.session['fdesig']
    u=complaint.objects.filter(complaintto=t)
    return render(request,'complaintview.html',{'res':u})

def profilefaculty(request):
    s=request.session['faculty']
    m=faculty.objects.get(id=s)
    return render(request,'facultyprofile.html',{'res':m})


def ackform(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        date = request.POST.get('date')
        email = request.POST.get('email')
        ackmesg = request.POST.get('ackmesg')
        log = acknowledgement(name=name,date=date,email=email,ackmesg=ackmesg)
        log.save()
        return redirect(ackform)
    return render(request, 'acknowledgement.html')
    
def ackview(request):
    m=request.session['useremail']
    n=acknowledgement.objects.filter(email=m)
    return render(request,'acknowledgementview.html',{'res':n})

def viewfaculty(request):
    u=faculty.objects.all()
    return render(request,'facultyview.html',{'res':u})

def viewadmin(request):
    return render(request, 'adminprofile.html')

def viewstudent(request):
    u=register.objects.all()
    return render(request,'studentview.html',{'res':u})

def sdelete(request,id):
    mark=register.objects.get(pk=id)
    mark.delete()
    return redirect(viewstudent)

def cmpltviewadmin(request):
    u=complaint.objects.all()
    return render(request,'complaintviewadmin.html',{'res':u})

def ackfaculty(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        designation=request.POST.get('designation')
        name = request.POST.get('name')
        email = request.POST.get('email')
        ackmesg = request.POST.get('ackmesg')
        log = facack(date=date,designation=designation,name=name,email=email,ackmesg=ackmesg)
        log.save()

    return render(request, 'facultyackadmin.html')

def viewfacultyack(request):
    t=request.session['email']
    u=request.session['fdesig']
    h=facack.objects.filter(email=t,designation=u)
    return render(request,'viewfacultyackadmin.html',{'res':h})

def cupdate(request,id):
    cm=complaint.objects.get(pk=id)
    return render(request,'complaintupdate.html',{'res':cm})

def cmupdate(request, id):
    cm = complaint.objects.get(pk=id)
    
    if request.method == 'POST':
        complaintto = request.POST.get('complaintto')
        date = request.POST.get('date')
        name = request.POST.get('name')
        email = request.POST.get('email')
        complaintmesg = request.POST.get('complaintmesg')
        status = request.POST.get('status')
        userid = cm.userid
        log = complaint(id=id, userid=userid, complaintto=complaintto, date=date, name=name, email=email, complaintmesg=complaintmesg, status=status)
        log.save()
        return redirect(viewcomplaint)
    return render(request, 'complaintform.html', {'res': cm})


def profilestudent(request):
    s=request.session['student']
    m=register.objects.get(id=s)
    return render(request,'profile.html',{'res':m})
def supdate(request):
    s=request.session['student']
    m=register.objects.get(id=s)
    return render(request,'studentupdate.html',{'res':m})

def updatestudent(request,id):
    if request.method == 'POST':
        userphoto = request.FILES['userphoto']
        up = FileSystemStorage()
        img = up.save(userphoto.name, userphoto)
        useremail = request.POST.get('useremail')
        username = request.POST.get('username')
        userphone = request.POST.get('userphone')
        password = request.POST.get('password')
        log = register(useremail=useremail, username=username, userphone=userphone, password=password, userphoto=userphoto,id=id)
        log.save()
        return redirect(profilestudent)
    return render(request, 'register.html')

complaintbox/templates/acknowledgement.html
{% load static %}
{% block content %}
{% include 'header.html' %}
    <div class="container" style=" width: 100%;">
        <form id="request" class="main_form" method="POST" action="{% url 'ackform' %}" enctype="multipart/form-data">

    <h1 class="cmplt">Acknowledgement Form</h1>
    {% csrf_token %}

    <div class="container cmplt_style ">
        <div class="row">
            
            <div class="col-12 col-md-6">
                <input class="cmplt_style" type="" placeholder="Name" name="name" ><br>
                <input class="cmplt_style" type="date" placeholder="YYYY-MM-DD" name="date" ><br>
                <input class="cmplt_style" type="email" placeholder="Student's Email" name="email"><br><br>
                <input type="" placeholder="Acknowlegement Message" name="ackmesg" id="id_ackmesg" style="height: 100px; width: 800px;border-color: rgb(13, 13, 13);" ><br><br>

                <button type="submit" style=" width: 250px;height: 50px; border-radius: 10px;background-color:orchid; text-align: center;" >Sumit Acknowledgement</button>
            </div>
        </div>
    </div>
    </form>
</div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
 
{% include 'footer.html' %}
{% endblock %}
    

complaintbox/templates/acknowledgementview.html
{% load static %}
{% block content %}
{% include 'header.html' %}

<div class="contact">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="titlepage text_align_center">
               <h2 class="tbhead">STUDENT DETAILS</h2>
               <table class="table" align="center">
                  <thead>
                    
                      <tr>
                          <th>ID</th>
                          <th>NAME</th>
                          <th>DATE</th>
                          <th>EMAIL</th>
                          <th>REPLY MSG</th>

                      </tr>
                  </thead>
                  <tbody>
                    {% for i in res %}

                      <tr>
                          <td>{{ i.id }}</td>                          
                          <td>{{ i.name }}</td>
                          <td>{{ i.date }}</td>
                          <td>{{ i.email }}</td>
                          <td>{{ i.ackmesg }}</td>
                          
                      </tr>
                      {% endfor %}

                  </tbody><br>
              </table><br><br><br><br><br><br>
             </div>
          </div>
       </div>
    </div>
 </div>
{% include 'footer.html' %}
{% endblock %}

complaintbox/templates/adminprofile.html
{% load static %}
{% block content %}
{% include 'header.html' %}

<section class="vh-100" style="background-color:rgba(74, 10, 134, 0.508);">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
              <h5>ADMIN</h5>
              <i class="far fa-edit mb-5"></i>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>Information</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Email</h6>
                    <p class="text-muted">admin@gmail.com</p>
                  </div>
                
                </div>

                  <div class="col-6 mb-3">
                    <h6>Password</h6>
                    <p class="text-muted">admin</p>
                  </div>
                </div>
                <div class="d-flex justify-content-start">
                  <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
 
  {% include 'footer.html' %}
{% endblock %}

complaintbox/templates/complaintupdate.html
{% load static %}
{% block content %}
{% include 'header.html' %}
    <div class="container" style=" width: 100%;">
    <form id="request" class="main_form" method="POST" action="cmupdate/{{res.id}}" enctype="multipart/form-data">

    <h1 class="cmplt">Update Complaint Form</h1>
    {% csrf_token %}

    
    <div class="container cmplt_style ">
        <div class="row">
            
            <div class="col-12 col-md-6">
                <select class="cmplt_style" id="complaintto" name="complaintto">
                    <option value="" {% if res.complaintto == "" %}selected{% endif %}>Select Whom you are sending the complaint:</option>
                    <option value="Trainer" {% if res.complaintto == "Trainer" %}selected{% endif %}>Trainer</option>
                    <option value="HR" {% if res.complaintto == "HR" %}selected{% endif %}>HR</option>
                    <option value="operations" {% if res.complaintto == "operations" %}selected{% endif %}>operations</option>
                </select>
                
                  
                <br>
                <input class="cmplt_style" type="date" placeholder="YYYY-MM-DD" name="date" value="{{res.date}}"><br>
                <input class="cmplt_style" type="text" placeholder="Name" name="name" value="{{res.name}}"><br>
                <input class="cmplt_style" type="email" placeholder="Email" name="email" value="{{res.email}}"><br><br>
                <input type="text" placeholder="Message" name="complaintmesg" value="{{res.complaintmesg}}" style="height: 100px; width: 800px;border-color: rgb(13, 13, 13);" ><br>
                <input class="cmplt_style" type="text" placeholder="Status" name="status" value="{{res.status}}"><br><br>

                <button style=" width: 190px;height: 50px; border-radius: 10px;background-color: orchid; text-align: center;" type="submit">Update</button>
            </div>
        </div>
    </div><br><br><br><br><br><br><br><br><br>
    </form><br><br><br><br><br><br>
</div><br><br><br><br><br><br><br><br>


{% include 'footer.html' %}
{% endblock %}

complaintbox/templates/complaintview.html
{% load static %}
{% block content %}
{% include 'header.html' %}

<div class="contact">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="titlepage text_align_center">
               <h2 class="tbhead">COMPLAINT MESSAGES</h2>
               <table class="table" align="center">
                  <thead>
                      <tr>
                          <th>ID</th>
                          <th>DATE</th>
                          <th>EMAIL</th>
                          <th>MESSAGE</th>
                          <th>STATUS</th>
                          <th>UPDATE</th>


                      </tr>
                  </thead>
                  <tbody>
                  {% for i in res %}
                      <tr>
                          <td>{{ i.id }}</td>
                          <td>{{ i.date }}</td>
                          <td>{{ i.email }}</td>
                          <td>{{ i.complaintmesg }}</td>
                          <td>{{ i.status }}</td>
                          <td><a href="{% url 'cupdate' id=i.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                          </svg></a></td>

                      </tr>
                  {% endfor %}
                  </tbody><br>
              </table><br><br><br><br><br><br>
             </div>
          </div>
       </div>
    </div>
 </div>
{% include 'footer.html' %}
{% endblock %}

complaintbox/templates/complaintviewadmin.html
{% load static %}
{% block content %}
{% include 'header.html' %}

<div class="contact">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="titlepage text_align_center">
               <h2 class="tbhead">COMPLAINT MESSAGES</h2>
               <table class="table" align="center">
                  <thead>
                      <tr>
                          <th>ID</th>
                          <th>DATE</th>
                          <th>EMAIL</th>
                          <th>MESSAGE</th>
                          <th>STATUS</th>


                      </tr>
                  </thead>
                  <tbody>
                  {% for i in res %}
                      <tr>
                          <td>{{ i.id }}</td>
                          <td>{{ i.date }}</td>
                          <td>{{ i.email }}</td>
                          <td>{{ i.complaintmesg }}</td>
                          <td>{{ i.status }}</td>
                         

                      </tr>
                  {% endfor %}
                  </tbody><br>
              </table><br><br><br><br><br><br>
             </div>
          </div>
       </div>
    </div>
 </div>
{% include 'footer.html' %}
{% endblock %}

complaintbox/templates/facultyackadmin.html
{% load static %}
{% block content %}
{% include 'header.html' %}
    <div class="container" style=" width: 100%;">
        <form id="request" class="main_form" method="POST" action="{% url 'ackfaculty' %}" enctype="multipart/form-data">

    <h1 class="cmplt">Acknowledgement Form</h1>
    {% csrf_token %}

    <div class="container cmplt_style ">
        <div class="row">
            
            <div class="col-12 col-md-6">
                <input class="cmplt_style" type="date" placeholder="YYYY-MM-DD" name="date"><br>
                <input class="cmplt_style" type="text" placeholder="Designation" name="designation"><br>

                <input class="cmplt_style" type="text" placeholder="Name" name="name" ><br>

                <input class="cmplt_style" type="email" placeholder="Faculty's Email" name="email"><br><br>
                <input type="text" placeholder="Acknowlegement Message" name="ackmesg"  style="height: 100px; width: 800px;border-color: rgb(13, 13, 13);" ><br><br>

                <button type="submit" style=" width: 250px;height: 50px; border-radius: 10px;background-color:orchid; text-align: center;" >Sumit Acknowledgement</button>
            </div>
        </div>
    </div>
    </form>
</div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
 
{% include 'footer.html' %}
{% endblock %}
    

complaintbox/templates/facultylogin.html
{% load static %}
{% block content %}
{% include 'header.html' %}

    <div class="container reg" style="background-color:rgba(74, 10, 134, 0.533);border-radius: 170px;"><br><br>
        <div class="row">
            <div class="col-12 col-md-6">
                <img src="{% static 'image/reg.webp' %}" class="img-fluid imgb" alt="...">
            </div>
            <div class="col-12 col-md-6">
                <form id="request" class="main_form" method="POST" action="{% url 'facultylog' %}" enctype="multipart/form-data">
                    <h1 style="margin-left: 150px;">Login</h1><br><br>
                {% csrf_token %}

                <div class="container reg2">
                    <div class="row">
                        <div class="col-12">
                            <input class="style1" type="designation" placeholder="Designation" name="designation"><br><br>

                            <input class="style1" type="email" placeholder="Email" name="email"><br><br>
                           <input class="style1" type="password" placeholder="Password" name="password"><br><br>
                            <button class="reg3button" type="submit">Login</button><br><br>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
    {% endblock %}

complaintbox/templates/facultyprofile.html
{% load static %}
{% block content %}
{% include 'header.html' %}

<section class="vh-100" style="background-color:rgba(74, 10, 134, 0.508);">
  <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-6 mb-4 mb-lg-0">
              <div class="card mb-3" style="border-radius: .5rem;">
                <div class="row g-0">
                  <div class="col-md-4 gradient-custom text-center text-white"
                    style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;"><br><br><br><br>
                    <h5>WELCOME</h5>
                    <i class="far fa-edit mb-5"></i>
                  </div>
                  <div class="col-md-8">
                    <div class="card-body p-4">
                      <h6>Information</h6>
                      <hr class="mt-0 mb-4">
                      <div class="row pt-1">
                        <div class="col-6 mb-3">
                            <h6>DESIGNATION</h6>
                            <p class="text-muted">{{res.designation}}</p>
                          </div>
                        <div class="col-6 mb-3">
                            <h6>NAME</h6>
                            <p class="text-muted">{{res.name}}</p>
                          </div>
                        <div class="col-6 mb-3">
                          <h6>EMAIL</h6>
                          <p class="text-muted">{{res.email}}</p>
                        </div>
                      
                        <div class="col-6 mb-3">
                            <h6>PASSWORD</h6>
                            <p class="text-muted">{{res.password}}</p>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
 
  {% include 'footer.html' %}
{% endblock %}

complaintbox/templates/facultyview.html
{% load static %}
{% block content %}
{% include 'header.html' %}

<div class="contact">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="titlepage text_align_center">
               <h2 class="tbhead">FACULTY DETAILS</h2>
               <table class="table" align="center">
                  <thead>
                      <tr>
                          <th>ID</th>
                          <th>DESIGNATION</th>
                          <th>NAME</th>
                          <th>EMAIL</th>
                          <th>PASSWORD</th>
                      </tr>
                  </thead>
                  <tbody>
                  {% for i in res %}
                      <tr>
                          <td>{{ i.id }}</td>
                          <td>{{ i.designation }}</td>

                          <td>{{ i.name }}</td>
                          <td>{{ i.email }}</td>
                          <td>{{ i.password }}</td>
                      </tr>
                  {% endfor %}
                  </tbody>
              </table>
             </div>
          </div>
       </div>
    </div>
 </div>
{% include 'footer.html' %}
{% endblock %}

complaintbox/templates/register.html
{% load static %}
{% block content %}
{% include 'header.html' %}

    <div class="container reg" style="background-color:rgba(74, 10, 134, 0.533);border-radius: 170px;"><br><br>
        <div class="row">
            <div class="col-12 col-md-6">
                <img src="{% static 'image/reg.webp' %}" class="img-fluid imgb" alt="...">
            </div>
            <div class="col-12 col-md-6">
                <form id="request" class="main_form" method="POST" action="{% url 'studentreg' %}" enctype="multipart/form-data">
                    <h1 style="margin-left: 150px;">Registration</h1><br><br>
                {% csrf_token %}

                <div class="container reg2">
                    <div class="row">
                        <div class="col-md-12">
                            <input class="style" placeholder="Name*" type="file" name="userphoto"> 
                         </div><br><br>
                        <div class="col-12">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-envelope svg_style" viewBox="0 0 16 16">
                                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
                            </svg><input class="style1" type="email" placeholder="Email" name="useremail"><br>
                            <br>
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-fill svg_style" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                            </svg><input class="style1" type="" placeholder="Name" name="username" id="id_username"><br>
                            <br>
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-telephone-fill svg_style" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                            </svg><input class="style1" type="" placeholder="Phonenumber" name="userphone" id="id_userphone"><br>
                            <br>
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-key-fill svg_style" viewBox="0 0 16 16">
                                <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                            </svg><input class="style1" type="password" placeholder="Password" name="password"><br><br>
                            <button class="reg3button" type="submit">Register</button><br><br>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
    {% endblock %}